### ISSUE TITLE
Maven integration tests should be implemented

### ISSUE THREAD

**Issue by pfistererm** [aposin/LicenseScout#10]
Maven integration tests for the LicenseScout should be implemented.
This will assure that certain Maven configuration parameters are working correctly.

# Feature request

## Expected Behavior - What where you expecting to happen?

The POM of the main project (org.aposin.licensescout.core/pom.xml) should contain a profile that executes integration tests, so that they can be easily executed during a CI build.

## Current Behavior - What happens?
No integration tests are present. We have no assurance that the LicenseScout as a whole works.

## Possible Solution
The recommended approach for testing complete maven plugins is to use the Maven invoker plugin (https://maven.apache.org/plugins/maven-invoker-plugin/) Besides executing a separate Maven run, it can also be used to verify results by checking text content of files (in this case the resulting license reports).

(See also resource linked below)

## Context
The proposed approach of integration testing is running specially customized POM files in a separate reactor run. So it is most closely to running the LicenseScout in a real build environment.

## Notes and further information

See also https://maven.apache.org/plugin-developers/plugin-testing.html

**Comment by holzerma** [comment]
we decided to take this into account. 
PR for this issue are highly welcome!

**Comment by pfistererm** [comment]
Closed because with #98 integration tests are now also integrated into the Travis build.
