### ISSUE TITLE
LicenseScout needs a logo

### ISSUE THREAD

**Issue by MarRothm** [aposin/LicenseScout#17]
# Feature request

## Expected Behavior - What where you expecting to happen?
LicenseScout needs a logo to distinguish our various projects.

## Current Behavior - What happens?
LicenseScout has no logo.

## Possible Solution
Somebody to sketch a text based logo.

## Context
Marketing

**Comment by holzerma** [comment]
we decided to take this into account.
Contributions for this feature are highly welcome!

**Comment by StefanFranzWeiser** [comment]
Maybe, a combination of a [magnifying glass](https://www.flaticon.com/free-icon/search_149309) and a [libra](https://www.flaticon.com/free-icon/balance_122112)?

**Comment by MarRothm** [comment]
I played around with Looka and like those ...
![image](https://user-images.githubusercontent.com/38973581/59489794-72d60780-8e83-11e9-8dff-9b8395ab82ca.png)

Attention: these logos are not for free!

**Comment by holzerma** [comment]
i really like the "scout" -> i will try to find/create something similar which is compatible for us

**Comment by MarRothm** [comment]
What about this? Logo is from icons8.com


![LicenseScout_logo](https://user-images.githubusercontent.com/38973581/62774678-c80a5000-baa5-11e9-900b-cf28b2b69647.png)

**Comment by RoliSommer** [comment]
i like it :-)

**Comment by rubyology** [comment]
Maybe something like this?
![License Scout Suggestion Ruby_01](https://user-images.githubusercontent.com/54358186/63433935-5e366280-c424-11e9-9b42-3839d2fe934d.png)

**Comment by MarRothm** [comment]
Also a nice one. Maintainers, decide for a logo!

**Comment by RoliSommer** [comment]
for me it's too much connected to a Safari trip haha

**Comment by holzerma** [comment]
Thanks for all your ideas! We will have our next maintainer meetup in the upcoming week. @aposin/maintainers There we will take a decision.

**Comment by holzerma** [comment]
we decided to go with the "tent" as a blueprint, i will create a more detailed one

**Comment by MarRothm** [comment]
![d06e7ed3-7c69-46f7-b12c-e9fc46425271](https://user-images.githubusercontent.com/38973581/66256188-ac60b480-e78b-11e9-89ad-7668590475ea.png)

**Comment by StefanFranzWeiser** [comment]
Beautiful. 👍

**Comment by d-gs** [comment]
+1 for https://github.com/aposin/LicenseScout/issues/17#issuecomment-538653675

**Comment by RoliSommer** [comment]
like it too - Looks cool

**Comment by pfistererm** [comment]
+1
