### ISSUE TITLE
LicenseScout should be released on Maven central

### ISSUE THREAD

**Issue by pfistererm** [aposin/LicenseScout#22]
LicenseScout should be released on Maven central

# Feature request

## Expected Behavior - What where you expecting to happen?
When doing a release (exact process is open) the release of the LicenseScout should be published on Maven central.

## Current Behavior - What happens?

No public binary release of LicenseScout available.

## Possible Solution
Here is a Tutorial 'How to Publish Your Artifacts to Maven Central':
https://dzone.com/articles/publish-your-artifacts-to-maven-central

The first step we need to do is to acquire a Sonatype Jira account and then create a JIRA ticket requesting a project hosting as described in the Tutorial linked above.

## Context
It would ease using the LicenseScout for other projects significantly if it would be publicly available.
It would free users from doing a build of the LicenseScout on their own - they could use the binary plugin from Maven central.

**Comment by pfistererm** [comment]
@holzerm: can you request the Sonatype JIRA account?

**Comment by holzerma** [comment]
Hi, @pfistererm : this is already done. @d-gs  and myself are already permitted to create a new project on maven central.

**Comment by holzerma** [comment]
referes to #32 , both should be done together

**Comment by pfistererm** [comment]
Just managed to do the first release. See https://oss.sonatype.org/#nexus-search;quick~aposin

**Comment by pfistererm** [comment]
@holzerma A task for you: we can now add a Maven central badge to the README. See https://github.com/softwaremill/maven-badges

**Comment by pfistererm** [comment]
Now that release is working, point remaining to do are:
- solve our infrastructure problems so that we can do the release without circumventing the network
- adapt the documentation so that the examples refer to a released stable version
- adapt the maintainer documentation to explain how to use password encryption

What we might consider in the future:
- automatic snapshot releases on every merged PR

**Comment by pfistererm** [comment]
Closed because finally resolved by #106.
