### ISSUE TITLE
Assure that line endings are consistent throughout the project

### ISSUE THREAD

**Issue by pfistererm** [aposin/LicenseScout#26]
Assure that line endings are consistent throughout the project

# Feature request

## Expected Behavior - What where you expecting to happen?
When cloning a repository, either line endings should be converted to the convention of the local OS and back when doing a commit, or it should be enforced that line endings never change.

## Current Behavior - What happens?

When cloning the repository to a Windows system, line endings in source files are converted to Windows line endings. This is shown as differences throughout the whole file, so that the actual change is hard to detect. Automatic converting back to a "server" line ending does not seem to work. (See e.g. the changes in CryptUtilTest: https://github.com/aposin/LicenseScout/pull/24/files)

## Possible Solution
Line ending conversion can be configured either locally to the GIT tool or maybe centrally for the repository by adding a .gitattributes file. Details need to be worked out.

**Comment by d-gs** [comment]
More information about the enforcement with the gitattributes at the check in/out policies could be found here: https://git-scm.com/docs/gitattributes#_checking_out_and_checking_in (concretely, relevant configuration are `text` and `eol`).

Also, it might be possible to setup a check on the CI for the enforced line endings to avoid mixing them up.

**Comment by d-gs** [comment]
Closed by #42
