### ISSUE TITLE
Hacktoberfest: Fix code quality issues

### ISSUE THREAD

**Issue by d-gs** [aposin/LicenseScout#35]
# Contribute to **LicenseScout** for the Hacktoberfest by fixing code quality issues of the project!

* Sign up for Hacktoberfest to be sure that your contribution is tracked on https://hacktoberfest.digitalocean.com/profile
* Check the current status of the code quality on the project's Codacy site: https://app.codacy.com/manual/aposin-bot/LicenseScout/dashboard
* Identify relevant code quality issues to fix
* Fix the issues and make a Pull Request (PR). If this is your first time making a PR, check the following section on the Open Source Guide from GitHub: https://opensource.guide/how-to-contribute/#opening-a-pull-request

ℹ️ Please, follow the quality guidelines for Hacktoberfest described in #38

Thank you and happy Hacktoberfest!

**Comment by davu-all** [comment]
Closing as Hacktoberfest is over. Thanks to all participants!
