### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by d-gs** [aposin/LicenseScout#38]
# Get a t-shirt from participating in this year Hacktoberfest by contributing to _LicenseScout_

## Quality Standards for PRs

To maintain the Hacktoberfest quality standards and values, pull-requests (PRs) during October **must** follow the rules specified in this issue. If any of the rules is not followed, we would mark the PR as `invalid` and it won't count for the Hacktoberfest contributions.

* Follow the contribution guidelines and code of conduct of the repository
* Commits **must** be authored by the PRs initiator
* Contributions **must** come from the author's fork or branch
* Fix of typos or formatting is **allowed**,  but **only** if it is not only a bare attempt to get a +1 count for the Hacktoberfest (e.g., one-word change or single-space removal). You can see an example of a good-quality typo-fixing/formatting PR here: https://github.com/aposin/openinsuranceplatform/pull/9

## Where to start

* Sign-in for the Hacktoberfest [here](https://hacktoberfest.digitalocean.com/profile).
* Check our [`Hacktoberfest`-labeled issues](https://github.com/aposin/LicenseScout/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest).  Some of them are specific to the Hacktoberfest (e.g., #34 and #35), and contain general guidelines to identify contributions to improve the quality of this project.
* Before opening a PR for other issues, please ask the maintainers if you can take it over.

-- -

_Find more information about the Hacktoberfest [here](https://hacktoberfest.digitalocean.com)_

**Comment by davu-all** [comment]
Closing as Hacktoberfest is over. Thanks to all participants!
