### ISSUE TITLE
Contributor License Agreement should be formatted for 

### ISSUE THREAD

**Issue by rmlekus** [aposin/LicenseScout#55]
# Summary

The contributor license agreement CLA presented upon creating the first pull request is hard to read (tested within Chrome Browser 77.0.3865.120 / Mac OS 10.14). It seems like line breaks between paragraphs and sub-sections of the text are not displayed when presenting the CLA on https://cla-assistant.io/aposin

![image](https://user-images.githubusercontent.com/2836548/67626386-17f9e700-f84b-11e9-896f-58a49d787c6f.png)

# Feature request

CLA should be formatted to allow for an eye-friendly review before signing the agreement.

**Comment by rmlekus** [comment]
Example for suggested practice regarding formatting (markdown) and Version  (as to my personal opinion, of cause) : https://gist.github.com/jobara/b932eeb8bcb226583ead8b86a51b4099

**Comment by d-gs** [comment]
@holzerma - could you have a look to this? Thanks for the report, @rmlekus!

**Comment by holzerma** [comment]
i updated the CLA to a new GIST, nevertheless gist does not render like a typical markdown it seems. But much cleaner now. Thansk for the issue.

**Sideeffect: everybody has to resign the CLA now.**

**Comment by rmlekus** [comment]
Great, has got a much better "user/developer" experience now:
![image](https://user-images.githubusercontent.com/2836548/67889228-bbe6d980-fb4e-11e9-90a1-d2d77e6f927f.png)
