### ISSUE TITLE
Codecov check should fail if jacoco does not create a report instead of hanging

### ISSUE THREAD

**Issue by davu-all** [aposin/LicenseScout#76]
As we realized in PR #25 , if for any reason the jacoco plugin is not able to generate a report, the codecov check hangs forever.

A more consistent behavior would be that this check fails, making the developers aware that some changes in their PR caused the problem.

# Feature request

## Expected Behavior - What where you expecting to happen?

If any change prevents the jacoco plugin to generate the report the codecov check fails instead of hanging forever.

## Current Behavior - What happens?

If  the jacoco plugin to generate the report the codecov check hangs forever.

## Possible Solution

Adapt the travis.yml build configuration file to fail if the jacoco report is not generated.

**Comment by holzerma** [comment]
closed by #78 . thanks a lot for your contribution @davu-all & @pfistererm
