### ISSUE TITLE
travis configuration should be extended to run the LicenseScout on itself

### ISSUE THREAD

**Issue by pfistererm** [aposin/LicenseScout#9]
The travis configuration for this project currently runs the common maven license check, but does not run the more advanced LicenseScout.

# Feature request

## Expected Behavior - What where you expecting to happen?
the travis configuration should have an additional target that runs the LicenseScout on itself.

## Current Behavior - What happens?

Currently, only standard maven license checks are run.

## Possible Solution

There are already configurations and maven projects to do this task.

* an example configuration for the LicenseScout that is tailored to run the check on itself is present in the project org.aposin.licensescout.configuration.sample
* a maven setup to execute the check is present in the project org.aposin.licensescout.licensereport

These can be used to implement the travis run.

**Comment by holzerma** [comment]
we decided to take this into account. pull requests for this issue are highly welcome!

**Comment by d-gs** [comment]
### Additional information
PRs should automatically show to the contributor that the NOTICE.txt should be either manually updated or generated by LicenseScount on itself. For example, #14 missed the license information in the NOTICE.txt, and it required to be pointed out by the reviewer (in this case, @holzerma). Automatic scan and notification on each PR will improve maintenance.

**Comment by pfistererm** [comment]
Closed because is now achieved with #99 and #100.
